import type { Metadata } from 'next';
import { Source_Sans_3 } from 'next/font/google';
import '../styles/globals.css';

// importing Source Sans like this will apply it as the default
// font throughout the whole application. This method uses some
// NextJS features to make font loading faster
const sourceSans = Source_Sans_3({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Federal Bureau of Fake Forms',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={sourceSans.className}>{children}</body>
    </html>
  );
}
